# Generated by Django 4.2 on 2023-05-03 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("anticoru", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="messageuser", name="eid",),
    ]
