# Generated by Django 4.2 on 2023-06-26 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("anticoru", "0002_remove_messageuser_eid_alter_randomuser_table_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterModelTable(name="customuser", table=None,),
    ]
