# Generated by Django 4.2 on 2023-06-26 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("anticoru", "0003_alter_customuser_options_alter_customuser_table"),
    ]

    operations = [
        migrations.DeleteModel(name="CustomUser",),
    ]
