# Generated by Django 4.2 on 2023-06-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anticoru", "0007_customuser"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="mobile",),
        migrations.AddField(
            model_name="customuser",
            name="is_student",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_teacher",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="mailing_address",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
