# Generated by Django 4.2 on 2023-06-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anticoru", "0012_alter_messageuser_m_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messageuser",
            name="m_audio",
            field=models.FileField(upload_to="documents/%Y/%m/%d"),
        ),
        migrations.AlterField(
            model_name="messageuser",
            name="m_image",
            field=models.FileField(upload_to="documents/%Y/%m/%d"),
        ),
        migrations.AlterField(
            model_name="messageuser",
            name="m_video",
            field=models.FileField(upload_to="documents/%Y/%m/%d"),
        ),
    ]
