# Generated by Django 4.2 on 2023-06-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anticoru", "0014_remove_messageuser_m_audio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="messageuser",
            name="m_audio",
            field=models.FileField(default=1, upload_to="documents/%Y/%m/%d"),
            preserve_default=False,
        ),
    ]
